// All users Auth
export const userAuth = {
  // Client Auth
  CLIENT_SIGN_UP_REQUEST: "CLIENT_SIGN_UP_REQUEST",
  CLIENT_SIGN_UP_SUCCESS: "CLIENT_SIGN_UP_SUCCESS",
  CLIENT_SIGN_UP_FAIL: "CLIENT_SIGN_UP_FAIL",
  CLIENT_LOGIN_REQUEST: "CLIENT_LOGIN_REQUEST",
  CLIENT_LOGIN_SUCCESS: "CLIENT_LOGIN_SUCCESS",
  CLIENT_LOGIN_FAIL: "CLIENT_LOGIN_FAIL",
  CLIENT_LOGOUT_SUCCESS: "CLIENT_LOGOUT_SUCCESS",
  CLIENT_LOGOUT_REQUEST: "CLIENT_LOGOUT_REQUEST",

  // Freelance Auth
  FREELANCER_SIGN_UP_SUCCESS: "FREELANCER_SIGN_UP_SUCCESS",
  FREELANCER_SIGN_UP_FAIL: "FREELANCE_SIGN_UP_FAIL",
  FREELANCER_SIGN_UP_REQUEST: "FREELANCE_SIGN_UP_REQUEST",
  FREELANCER_LOG_IN_SUCCESS: "FREELANCER_LOG_IN_SUCCESS",
  FREELANCER_LOG_IN_FAIL: "FREELANCER_LOG_IN_FAIL",
  FREELANCER_LOG_IN_REQUEST: "FREELANCER_LOG_IN_REQUEST",
  FREELANCER_LOGOUT_SUCCESS: "FREELANCER_LOGOUT_SUCCESS",
  FREELANCER_LOGOUT_REQUEST: "FREELANCER_LOGOUT_REQUEST",

  // Admin Auth
  ADMIN_REGISTRATION_SUCCESS: "ADMIN_REGISTRATION_SUCCESS",
  ADMIN_REGISTRATION_FAIL: "ADMIN_REGISTRATION_FAIL",
  ADMIN_REGISTRATION_REQUEST: "ADMIN_REGISTRATION_REQUEST",
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
  ADMIN_LOGOUT_SUCCESS: "ADMIN_LOGOUT_SUCCESS",
  ADMIN_LOGOUT_REQUEST: "ADMIN_LOGOUT_REQUEST",
};

export const LOGIN_LOADING_SUCCESS = "LOGIN_LOADING_SUCCESS";
export const GET_ORDERS_LOADER = "GET_ORDERS_LOADER";
export const GET_GIGS_LOADER = "GET_GIGS_LOADER";
export const GET_REPORTS_LOADER = "GET_REPORTS_LOADER";
export const GET_NOTIFICATIONS_LOADER = "GET_NOTIFICATIONS_LOADER";
export const GET_BLOGS_LOADER = "GET_BLOGS_LOADER";

// Freelancers Types
export const GET_FREELANCER_PROFILE_SUCCESS = "GET_FREELANCER_PROFILE_SUCCESS";
export const GET_FREELANCER_PROFILE_FAIL = "GET_FREELANCER_PROFILE_FAIL";
export const GET_FREELANCER_PROFILE_REQUEST = "GET_FREELANCER_PROFILE_REQUEST";

export const DELETE_FREELANCER_ACCOUNT_SUCCESS =
  "DELETE_FREELANCER_ACCOUNT_SUCCESS";
export const DELETE_FREELANCER_ACCOUNT_FAIL = "DELETE_FREELANCER_ACCOUNT_FAIL";
export const DELETE_FREELANCER_ACCOUNT_REQUEST =
  "DELETE_FREELANCER_ACCOUNT_REQUEST";

export const FORGET_FREELANCER_PASSWORD_SUCCESS =
  "FORGET_FREELANCER_PASSWORD_SUCCESS";
export const FORGET_FREELANCER_PASSWORD_FAIL =
  "FORGET_FREELANCER_PASSWORD_FAIL";
export const FORGET_FREELANCER_PASSWORD_REQUEST =
  "FORGET_FREELANCER_PASSWORD_REQUEST";

export const VERIFY_FREELANCER_TOKEN_SUCCESS =
  "VERIFY_FREELANCER_TOKEN_SUCCESS";
export const VERIFY_FREELANCER_TOKEN_FAIL = "VERIFY_FREELANCER_TOKEN_FAIL";
export const VERIFY_FREELANCER_TOKEN_REQUEST =
  "VERIFY_FREELANCER_TOKEN_REQUEST";

export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";
export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";

export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL";
export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";

export const RESET_FREELANCER_PASSWORD_SUCCESS =
  "RESET_FREELANCER_PASSWORD_SUCCESS";
export const RESET_FREELANCER_PASSWORD_FAIL = "RESET_FREELANCER_PASSWORD_FAIL";
export const RESET_FREELANCER_PASSWORD_REQUEST =
  "RESET_FREELANCER_PASSWORD_REQUEST";

export const ADD_FREELANCER_PAYMENT_SUCCESS = "ADD_FREELANCER_PAYMENT_SUCCESS";
export const ADD_FREELANCER_PAYMENT_FAIL = "ADD_FREELANCER_PAYMENT_FAIL";
export const ADD_FREELANCER_PAYMENT_REQUEST = "ADD_FREELANCER_PAYMENT_REQUEST";

export const GET_FREELANCER_PAYMENT_FAIL = "GET_FREELANCER_PAYMENT_FAIL";
export const GET_FREELANCER_PAYMENT_SUCCESS = "GET_FREELANCER_PAYMENT_SUCCESS";
export const GET_FREELANCER_PAYMENT_REQUEST = "GET_FREELANCER_PAYMENT_REQUEST";

export const DELETE_FREELANCER_PAYMENT_SUCCESS =
  "DELETE_FREELANCER_PAYMENT_SUCCESS";
export const DELETE_FREELANCER_PAYMENT_FAIL = "DELETE_FREELANCER_PAYMENT_FAIL";
export const DELETE_FREELANCER_PAYMENT_REQUEST =
  "DELETE_FREELANCER_PAYMENT_REQUEST";

export const ADD_EXCHANGE_SKILLS_SUCCESS = "ADD_EXCHANGE_SKILLS_SUCCESS";
export const ADD_EXCHANGE_SKILLS_FAIL = "ADD_EXCHANGE_SKILLS_FAIL";
export const ADD_EXCHANGE_SKILLS_REQUEST = "ADD_EXCHANGE_SKILLS_REQUEST";

export const GET_ALL_FREELANCER_EXCHANGE_SKILLS_SUCCESS =
  "GET_ALL_FREELANCER_EXCHANGE_SKILLS_SUCCESS";
export const GET_ALL_FREELANCER_EXCHANGE_SKILLS_FAIL =
  "GET_ALL_FREELANCER_EXCHANGE_SKILLS_FAIL";
export const GET_ALL_FREELANCER_EXCHANGE_SKILLS_REQUEST =
  "GET_ALL_FREELANCER_EXCHANGE_SKILLS_REQUEST";

export const GET_ALL_MY_EXCHANGE_SKILLS_SUCCESS =
  "GET_ALL_MY_EXCHANGE_SKILLS_SUCCESS";
export const GET_ALL_MY_EXCHANGE_SKILLS_FAIL =
  "GET_ALL_MY_EXCHANGE_SKILLS_FAIL";
export const GET_ALL_MY_EXCHANGE_SKILLS_REQUEST =
  "GET_ALL_MY_EXCHANGE_SKILLS_REQUEST";

export const UPDATE_EXCHANGE_SKILLS_SUCCESS = "UPDATE_EXCHANGE_SKILLS_SUCCESS";
export const UPDATE_EXCHANGE_SKILLS_FAIL = "UPDATE_EXCHANGE_SKILLS_FAIL";
export const UPDATE_EXCHANGE_SKILLS_REQUEST = "UPDATE_EXCHANGE_SKILLS_REQUEST";

export const CREATE_NEW_FREELANCER_CONVERSATION_SUCCESS =
  "CREATE_NEW_FREELANCER_CONVERSATION_SUCCESS";
export const CREATE_NEW_FREELANCER_CONVERSATION_FAIL =
  "CREATE_NEW_FREELANCER_CONVERSATION_FAIL";
export const CREATE_NEW_FREELANCER_CONVERSATION_REQUEST =
  "CREATE_NEW_FREELANCER_CONVERSATION_REQUEST";

export const GET_FREELANCER_MESSAGES_SUCCESS =
  "GET_FREELANCER_MESSAGES_SUCCESS";
export const GET_FREELANCER_MESSAGES_FAIL = "GET_FREELANCER_MESSAGES_FAIL";
export const GET_FREELANCER_MESSAGES_REQUEST =
  "GET_FREELANCER_MESSAGES_REQUEST";

export const FREELANCER_EXCHANGE_SKILL_PROPOSAL_SENT_SUCCESS =
  "FREELANCER_EXCHANGE_SKILL_PROPOSAL_SENT_SUCCESS";
export const FREELANCER_EXCHANGE_SKILL_PROPOSAL_SENT_FAIL =
  "FREELANCER_EXCHANGE_SKILL_PROPOSAL_SENT_FAIL";
export const FREELANCER_EXCHANGE_SKILL_PROPOSAL_SENT_REQUEST =
  "FREELANCER_EXCHANGE_SKILL_PROPOSAL_SENT_REQUEST";

export const FREELANCER_EXCHANGE_SKILL_PROPOSAL_UPDATE_SUCCESS =
  "FREELANCER_EXCHANGE_SKILL_PROPOSAL_UPDATE_SUCCESS";
export const FREELANCER_EXCHANGE_SKILL_PROPOSAL_UPDATE_FAIL =
  "FREELANCER_EXCHANGE_SKILL_PROPOSAL_UPDATE_FAIL";
export const FREELANCER_EXCHANGE_SKILL_PROPOSAL_UPDATE_REQUEST =
  "FREELANCER_EXCHANGE_SKILL_PROPOSAL_UPDATE_REQUEST";

export const DELETE_EXCHANGE_SKILL_REQUEST_SUCCESS =
  "DELETE_EXCHANGE_SKILL_REQUEST_SUCCESS";
export const DELETE_EXCHANGE_SKILL_REQUEST_FAIL =
  "DELETE_EXCHANGE_SKILL_REQUEST_FAIL";
export const DELETE_EXCHANGE_SKILL_REQUEST_REQUEST =
  "DELETE_EXCHANGE_SKILL_REQUEST_REQUEST";

export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_FAIL = "ACCEPT_REQUEST_FAIL";
export const ACCEPT_REQUEST_REQUEST = "ACCEPT_REQUEST_REQUEST";

export const REJECT_REQUEST_SUCCESS = "REJECT_REQUEST_SUCCESS";
export const REJECT_REQUEST_FAIL = "REJECT_REQUEST_FAIL";
export const REJECT_REQUEST_REQUEST = "REJECT_REQUEST_REQUEST";

export const GET_ALL_SUBMITTED_EXCHANGE_SKILLS_REQUESTS_SUCCESS =
  "GET_ALL_SUBMITTED_EXCHANGE_SKILLS_REQUESTS_SUCCESS";
export const GET_ALL_SUBMITTED_EXCHANGE_SKILLS_REQUESTS_FAIL =
  "GET_ALL_SUBMITTED_EXCHANGE_SKILLS_REQUESTS_FAIL";
export const GET_ALL_SUBMITTED_EXCHANGE_SKILLS_REQUESTS_REQUEST =
  "GET_ALL_SUBMITTED_EXCHANGE_SKILLS_REQUESTS_REQUEST";

export const GET_ALL_RECEIVED_EXCHANGE_SKILLS_REQUESTS_SUCCESS =
  "GET_ALL_RECEIVED_EXCHANGE_SKILLS_REQUESTS_SUCCESS";
export const GET_ALL_RECEIVED_EXCHANGE_SKILLS_REQUESTS_FAIL =
  "GET_ALL_RECEIVED_EXCHANGE_SKILLS_REQUESTS_FAIL";
export const GET_ALL_RECEIVED_EXCHANGE_SKILLS_REQUESTS_REQUEST =
  "GET_ALL_RECEIVED_EXCHANGE_SKILLS_REQUESTS_REQUEST";

export const DELETE_EXCHANGE_SKILLS_SUCCESS = "DELETE_EXCHANGE_SKILLS_SUCCESS";
export const DELETE_EXCHANGE_SKILLS_FAIL = "DELETE_EXCHANGE_SKILLS_FAIL";
export const DELETE_EXCHANGE_SKILLS_REQUEST = "DELETE_EXCHANGE_SKILLS_REQUEST";

export const GET_ALL_FREELANCER_JOBS_SUCCESS =
  "GET_ALL_FREELANCER_JOBS_SUCCESS";
export const GET_ALL_FREELANCER_JOBS_FAIL = "GET_ALL_FREELANCER_JOBS_FAIL";
export const GET_ALL_FREELANCER_JOBS_REQUEST =
  "GET_ALL_FREELANCER_JOBS_REQUEST";

export const COMPLETE_FREELANCER_PROFILE_SUCCESS =
  "COMPLETE_FREELANCER_PROFILE_SUCCESS";
export const COMPLETE_FREELANCER_PROFILE_FAIL =
  "COMPLETE_FREELANCER_PROFILE_FAIL";
export const COMPLETE_FREELANCER_PROFILE_REQUEST =
  "COMPLETE_FREELANCER_PROFILE_REQUEST";

export const UPDATE_FREELANCER_ACCOUNT_SUCCESS =
  "UPDATE_FREELANCER_ACCOUNT_SUCCESS";
export const UPDATE_FREELANCER_ACCOUNT_FAIL = "UPDATE_FREELANCER_ACCOUNT_FAIL";
export const UPDATE_FREELANCER_ACCOUNT_REQUEST =
  "UPDATE_FREELANCER_ACCOUNT_REQUEST";

export const CREATE_NEW_BLOG_REPLY_COMMENT_FREELANCER_SUCCESS =
  "CREATE_NEW_BLOG_REPLY_COMMENT_FREELANCER_SUCCESS";

export const CREATE_NEW_BLOG_REPLY_COMMENT_FREELANCER_FAIL =
  "CREATE_NEW_BLOG_REPLY_COMMENT_FREELANCER_FAIL";

export const CREATE_NEW_BLOG_REPLY_COMMENT_FREELANCER_REQUEST =
  "CREATE_NEW_BLOG_REPLY_COMMENT_FREELANCER_REQUEST";

export const GET_FREELANCER_REVIEWS_SUCCESS = "GET_FREELANCER_REVIEWS_SUCCESS";
export const GET_FREELANCER_REVIEWS_FAIL = "GET_FREELANCER_REVIEWS_FAIL";
export const GET_FREELANCER_REVIEWS_REQUEST = "GET_FREELANCER_REVIEWS_REQUEST";

export const GET_ALL_FREELANCERS_SUCCESS = "GET_ALL_FREELANCERS_SUCCESS";
export const GET_ALL_FREELANCERS_FAIL = "GET_ALL_FREELANCERS_FAIL";
export const GET_ALL_FREELANCERS_REQUEST = "GET_ALL_FREELANCERS_REQUEST";

export const GET_ALL_FREELANCER_ORDERS_SUCCESS =
  "GET_ALL_FREELANCER_ORDERS_SUCCESS";
export const GET_ALL_FREELANCER_ORDERS_FAIL = "GET_ALL_FREELANCER_ORDERS_FAIL";
export const GET_ALL_FREELANCER_ORDERS_REQUEST =
  "GET_ALL_FREELANCER_ORDERS_REQUEST";

export const READ_FREELANCER_NOTIFICATION_SUCCESS =
  "READ_FREELANCER_NOTIFICATION_SUCCESS";
export const READ_FREELANCER_NOTIFICATION_FAIL =
  "READ_FREELANCER_NOTIFICATION_FAIL";
export const READ_FREELANCER_NOTIFICATION_REQUEST =
  "READ_FREELANCER_NOTIFICATION_REQUEST";

export const GET_MY_FREELANCER_BLOGS_SUCCESS = "GET_MY_FREELANCER_BLOGS_FAIL";
export const GET_MY_FREELANCER_BLOGS_FAIL = "GET_MY_FREELANCER_BLOGS_FAIL";
export const GET_MY_FREELANCER_BLOGS_REQUEST =
  "GET_MY_FREELANCER_BLOGS_REQUEST";

export const GET_ALL_FREELANCER_EXCHANGE_SKILLS_ORDERS_SUCCESS =
  "GET_ALL_FREELANCER_EXCHANGE_SKILLS_ORDERS_SUCCESS";
export const GET_ALL_FREELANCER_EXCHANGE_SKILLS_ORDERS_FAIL =
  "GET_ALL_FREELANCER_EXCHANGE_SKILLS_ORDERS_FAIL";
export const GET_ALL_FREELANCER_EXCHANGE_SKILLS_ORDERS_REQUEST =
  "GET_ALL_FREELANCER_EXCHANGE_SKILLS_ORDERS_REQUEST";

export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";

export const CREATE_NEW_BLOG_COMMENT_SUCCESS =
  "CREATE_NEW_BLOG_COMMENT_SUCCESS";
export const CREATE_NEW_BLOG_COMMENT_FAIL = "CREATE_NEW_BLOG_COMMENT_SUCCESS";
export const CREATE_NEW_BLOG_COMMENT_REQUEST =
  "CREATE_NEW_BLOG_COMMENT_REQUEST";

export const CREATE_NEW_BLOG_REPLY_COMMENT_SUCCESS =
  "CREATE_NEW_BLOG_REPLY_COMMENT_SUCCESS";
export const CREATE_NEW_BLOG_REPLY_COMMENT_FAIL =
  "CREATE_NEW_BLOG_REPLY_COMMENT_FAIL";
export const CREATE_NEW_BLOG_REPLY_COMMENT_REQUEST =
  "CREATE_NEW_BLOG_REPLY_COMMENT_REQUEST";

export const GET_ALL_FREELANCER_BLOGS_SUCCESS =
  "GET_ALL_FREELANCER_BLOGS_SUCCESS";
export const GET_ALL_FREELANCER_BLOGS_FAIL = "GET_ALL_FREELANCER_BLOGS_FAIL";
export const GET_ALL_FREELANCER_BLOGS_REQUEST =
  "GET_ALL_FREELANCER_BLOGS_REQUEST";

export const GET_FREELANCER_ALL_REVIEWS_SUCCESS =
  "GET_FREELANCER_ALL_REVIEWS_SUCCESS";

export const GET_FREELANCER_ALL_REVIEWS_FAIL =
  "GET_FREELANCER_ALL_REVIEWS_FAIL";

export const GET_FREELANCER_ALL_REVIEWS_REQUEST =
  "GET_FREELANCER_ALL_REVIEWS_REQUEST";

export const GET_ALL_FREELANCER_REPORTS_SUCCESS =
  "GET_ALL_FREELANCER_REPORTS_SUCCESS";
export const GET_ALL_FREELANCER_REPORTS_FAIL =
  "GET_ALL_FREELANCER_REPORTS_FAIL";
export const GET_ALL_FREELANCER_REPORTS_REQUEST =
  "GET_ALL_FREELANCER_REPORTS_REQUEST";
// Proposal
export const FREELANCER_PROPOSAL_SENT_SUCCESS =
  "FREELANCER_PROPOSAL_SENT_SUCCESS";
export const FREELANCER_PROPOSAL_SENT_FAIL = "FREELANCER_PROPOSAL_SENT_FAIL";
export const FREELANCER_PROPOSAL_SENT_REQUEST =
  "FREELANCER_PROPOSAL_SENT_REQUEST";

export const CREATE_NEW_BLOG_SUCCESS = "CREATE_NEW_BLOG_SUCCESS";
export const CREATE_NEW_BLOG_FAIL = "CREATE_NEW_BLOG_FAIL";
export const CREATE_NEW_BLOG_REQUEST = "CREATE_NEW_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
// Admin
export const GET_ALL_FREELANCER_SUCCESS = "GET_ALL_FREELANCER_SUCCESS";
export const GET_ALL_FREELANCER_FAIL = "GET_ALL_FREELANCER_FAIL";
export const GET_ALL_FREELANCER_REQUEST = "GET_ALL_FREELANCER_REQUEST";
export const GET_ALL_CLIENTS_SUCCESS = "GET_ALL_CLIENTS_SUCCESS";
export const GET_ALL_CLIENTS_FAIL = "GET_ALL_CLIENTS_FAIL";
export const GET_ALL_CLIENTS_REQUEST = "GET_ALL_CLIENTS_REQUEST";
export const GET_ALL_ADMIN_EXCHANGE_SKILLS_SUCCESS =
  "GET_ALL_ADMIN_EXCHANGE_SKILLS_SUCCESS";
export const GET_ALL_ADMIN_EXCHANGE_SKILLS_FAIL =
  "GET_ALL_ADMIN_EXCHANGE_SKILLS_FAIL";
export const GET_ALL_ADMIN_EXCHANGE_SKILLS_REQUEST =
  "GET_ALL_ADMIN_EXCHANGE_SKILLS_REQUEST";
export const GET_ADMIN_JOB_PROPOSALS_SUCCESS =
  "GET_ADMIN_JOB_PROPOSALS_SUCCESS";
export const GET_ADMIN_EXCHANGE_SKILLS_REQUESTS_SUCCESS =
  "GET_ADMIN_EXCHANGE_SKILLS_REQUESTS_SUCCESS";
export const GET_ADMIN_EXCHANGE_SKILLS_REQUESTS_FAIL =
  "GET_ADMIN_EXCHANGE_SKILLS_REQUESTS_FAIL";
export const GET_ADMIN_EXCHANGE_SKILLS_REQUESTS_REQUEST =
  "GET_ADMIN_EXCHANGE_SKILLS_REQUESTS_REQUEST";
export const GET_ADMIN_JOB_PROPOSALS_FAIL = "GET_ADMIN_JOB_PROPOSALS_FAIL";
export const GET_ADMIN_JOB_PROPOSALS_REQUEST =
  "GET_ADMIN_JOB_PROPOSALS_REQUEST";
export const GET_ADMIN_BLOGS_SUCCESS = "GET_ADMIN_BLOGS_SUCCESS";
export const GET_ADMIN_BLOGS_FAIL = "GET_ADMIN_BLOGS_FAIL";
export const GET_ADMIN_BLOGS_REQUEST = "GET_ADMIN_BLOGS_REQUEST";
export const GET_ADMIN_ALL_GIGS_SUCCESS = "GET_ADMIN_ALL_GIGS_SUCCESS";
export const GET_ADMIN_ALL_GIGS_FAIL = "GET_ADMIN_ALL_GIGS_FAIL";
export const GET_ADMIN_ALL_GIGS_REQUEST = "GET_ADMIN_ALL_GIGS_REQUEST";
export const GET_ADMIN_JOBS_SUCCESS = "GET_ADMIN_JOBS_SUCCESS";
export const GET_ADMIN_JOBS_FAIL = "GET_ADMIN_JOBS_FAIL";
export const GET_ADMIN_JOBS_REQUEST = "GET_ADMIN_JOBS_REQUEST";
export const GET_ADMIN_ORDERS_SUCCESS = "GET_ADMIN_ORDERS_SUCCESS";
export const GET_ADMIN_ORDERS_FAIL = "GET_ADMIN_ORDERS_FAIL";
export const GET_ADMIN_ORDERS_REQUEST = "GET_ADMIN_ORDERS_REQUEST";
export const GET_ADMIN_FREELANCER_REVIEWS_SUCCESS =
  "GET_ADMIN_FREELANCER_REVIEWS_SUCCESS";
export const GET_ADMIN_FREELANCER_REVIEWS_FAIL =
  "GET_ADMIN_FREELANCER_REVIEWS_FAIL";
export const GET_ADMIN_FREELANCER_REVIEWS_REQUEST =
  "GET_ADMIN_FREELANCER_REVIEWS_REQUEST";
export const GET_ADMIN_BLOGS_COMMENTS_SUCCESS =
  "GET_ADMIN_BLOGS_COMMENTS_SUCCESS";
export const GET_ADMIN_BLOGS_COMMENTS_FAIL =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const GET_ADMIN_BLOGS_COMMENTS_REQUEST =
  "GET_ADMIN_BLOGS_COMMENTS_REQUEST";
export const GET_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS";
export const GET_ADMIN_BLOGS_REPLY_COMMENTS_FAIL =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const GET_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST";
/* DELETE */

export const DELETE_ALL_FREELANCER_SUCCESS = "DELETE_ALL_FREELANCER_SUCCESS";
export const DELETE_ALL_FREELANCER_FAIL = "DELETE_ALL_FREELANCER_FAIL";
export const DELETE_ALL_FREELANCER_REQUEST = "DELETE_ALL_FREELANCER_REQUEST";
export const DELETE_ALL_CLIENTS_SUCCESS = "DELETE_ALL_CLIENTS_SUCCESS";
export const DELETE_ALL_CLIENTS_FAIL = "DELETE_ALL_CLIENTS_FAIL";
export const DELETE_ALL_CLIENTS_REQUEST = "DELETE_ALL_CLIENTS_REQUEST";
export const DELETE_ALL_ADMIN_EXCHANGE_SKILLS_SUCCESS =
  "DELETE_ALL_ADMIN_EXCHANGE_SKILLS_SUCCESS";
export const DELETE_ALL_ADMIN_EXCHANGE_SKILLS_FAIL =
  "DELETE_ALL_ADMIN_EXCHANGE_SKILLS_FAIL";
export const DELETE_ALL_ADMIN_EXCHANGE_SKILLS_REQUEST =
  "DELETE_ALL_ADMIN_EXCHANGE_SKILLS_REQUEST";
export const DELETE_ADMIN_JOB_PROPOSALS_SUCCESS =
  "DELETE_ADMIN_JOB_PROPOSALS_SUCCESS";
export const DELETE_ADMIN_JOB_PROPOSALS_FAIL =
  "DELETE_ADMIN_JOB_PROPOSALS_FAIL";
export const DELETE_ADMIN_JOB_PROPOSALS_REQUEST =
  "DELETE_ADMIN_JOB_PROPOSALS_REQUEST";
export const DELETE_ADMIN_EXCHANGE_SKILLS_REQUESTS_SUCCESS =
  "DELETE_ADMIN_EXCHANGE_SKILLS_REQUESTS_SUCCESS";
export const DELETE_ADMIN_EXCHANGE_SKILLS_REQUESTS_FAIL =
  "DELETE_ADMIN_EXCHANGE_SKILLS_REQUESTS_FAIL";
export const DELETE_ADMIN_EXCHANGE_SKILLS_REQUESTS_REQUEST =
  "DELETE_ADMIN_EXCHANGE_SKILLS_REQUESTS_REQUEST";

export const DELETE_ADMIN_BLOGS_SUCCESS = "DELETE_ADMIN_BLOGS_SUCCESS";
export const DELETE_ADMIN_BLOGS_FAIL = "DELETE_ADMIN_BLOGS_FAIL";
export const DELETE_ADMIN_BLOGS_REQUEST = "DELETE_ADMIN_BLOGS_REQUEST";
export const DELETE_ADMIN_ALL_GIGS_SUCCESS = "DELETE_ADMIN_ALL_GIGS_SUCCESS";
export const DELETE_ADMIN_ALL_GIGS_FAIL = "DELETE_ADMIN_ALL_GIGS_FAIL";
export const DELETE_ADMIN_ALL_GIGS_REQUEST = "DELETE_ADMIN_ALL_GIGS_REQUEST";
export const DELETE_ADMIN_JOBS_SUCCESS = "DELETE_ADMIN_JOBS_SUCCESS";
export const DELETE_ADMIN_JOBS_FAIL = "DELETE_ADMIN_JOBS_FAIL";
export const DELETE_ADMIN_JOBS_REQUEST = "DELETE_ADMIN_JOBS_REQUEST";
export const DELETE_ADMIN_ORDERS_SUCCESS = "DELETE_ADMIN_ORDERS_SUCCESS";
export const DELETE_ADMIN_ORDERS_FAIL = "DELETE_ADMIN_ORDERS_FAIL";
export const DELETE_ADMIN_ORDERS_REQUEST = "DELETE_ADMIN_ORDERS_REQUEST";
export const DELETE_ADMIN_FREELANCER_REVIEWS_SUCCESS =
  "DELETE_ADMIN_FREELANCER_REVIEWS_SUCCESS";
export const DELETE_ADMIN_FREELANCER_REVIEWS_FAIL =
  "DELETE_ADMIN_FREELANCER_REVIEWS_FAIL";
export const DELETE_ADMIN_FREELANCER_REVIEWS_REQUEST =
  "DELETE_ADMIN_FREELANCER_REVIEWS_REQUEST";
export const DELETE_ADMIN_BLOGS_COMMENTS_SUCCESS =
  "DELETE_ADMIN_BLOGS_COMMENTS_SUCCESS";
export const DELETE_ADMIN_BLOGS_COMMENTS_FAIL =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const DELETE_ADMIN_BLOGS_COMMENTS_REQUEST =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST";
export const DELETE_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS";
export const DELETE_ADMIN_BLOGS_REPLY_COMMENTS_FAIL =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const DELETE_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST";

export const GET_ADMIN_MESSAGES_SUCCESS = " GET_ADMIN_MESSAGES_SUCCESS";
export const GET_ADMIN_MESSAGES_FAIL = " GET_ADMIN_MESSAGES_FAIL";
export const GET_ADMIN_MESSAGES_REQUEST = " GET_ADMIN_MESSAGES_REQUEST";

// Gigs
export const CREATE_NEW_GIG_SUCCESS = "CREATE_NEW_GIG_SUCCESS";
export const CREATE_NEW_GIG_FAIL = "CREATE_NEW_GIG_FAIL";
export const CREATE_NEW_GIG_REQUEST = "CREATE_NEW_GIG_REQUEST";

export const EDIT_GIG_SUCCESS = "EDIT_GIG_SUCCESS";
export const EDIT_GIG_FAIL = "EDIT_GIG_FAIL";
export const EDIT_GIG_REQUEST = "EDIT_GIG_REQUEST";

export const DELETE_GIG_SUCCESS = "DELETE_GIG_SUCCESS";
export const DELETE_GIG_FAIL = "DELETE_GIG_FAIL";
export const DELETE_GIG_REQUEST = "DELETE_GIG_REQUEST";

export const GET_ALL_GIGS_SUCCESS = "GET_ALL_GIGS_SUCCESS";
export const GET_ALL_GIGS_FAIL = "GET_ALL_GIGS_FAIL";
export const GET_ALL_GIGS_REQUEST = "GET_ALL_GIGS_REQUEST";

export const ACCEPT_GIG_ORDER_SUCCESS = "ACCEPT_GIG_ORDER_SUCCESS";
export const ACCEPT_GIG_ORDER_FAIL = "ACCEPT_GIG_ORDER_FAIL";
export const ACCEPT_GIG_ORDER_REQUEST = "ACCEPT_GIG_ORDER_REQUEST";

export const CREATE_NEW_GIG_ORDER_SUCCESS = "CREATE_NEW_GIG_ORDER_SUCCESS";
export const CREATE_NEW_GIG_ORDER_FAIL = "CREATE_NEW_GIG_ORDER_FAIL";
export const CREATE_NEW_GIG_ORDER_REQUEST = "CREATE_NEW_GIG_ORDER_REQUEST";

export const GET_MY_GIGS_SUCCESS = "GET_ALL_GIGS_SUCCESS";
export const GET_MY_GIGS_FAIL = "GET_ALL_GIGS_FAIL";
export const GET_MY_GIGS_REQUEST = "GET_ALL_GIGS_REQUEST";

// Jobs
export const CREATE_NEW_JOB_SUCCESS = "CREATE_NEW_JOB_SUCCESS";
export const CREATE_NEW_JOB_FAIL = "CREATE_NEW_JOB_FAIL";
export const CREATE_NEW_JOB_REQUEST = "CREATE_NEW_JOB_REQUEST";

export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_FAIL = "EDIT_JOB_FAIL";
export const EDIT_JOB_REQUEST = "EDIT_JOB_REQUEST";

export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";
export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";

export const GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS";
export const GET_ALL_JOBS_FAIL = "GET_ALL_JOBS_FAIL";
export const GET_ALL_JOBS_REQUEST = "GET_ALL_JOBS_REQUEST";

export const GET_ALL_JOBS_PROPOSALS_FOR_CLIENT_SUCCESS =
  " GET_ALL_JOBS_PROPOSALS_FOR_CLIENT_SUCCESS";
export const GET_ALL_JOBS_PROPOSALS_FOR_CLIENT_FAIL =
  " GET_ALL_JOBS_PROPOSALS_FOR_CLIENT_FAIL";
export const GET_ALL_JOBS_PROPOSALS_FOR_CLIENT_REQUEST =
  " GET_ALL_JOBS_PROPOSALS_FOR_CLIENT_REQUEST";

export const GET_FREELANCER_CLIENT_REVIEWS_SUCCESS =
  " GET_FREELANCER_CLIENT_REVIEWS_SUCCESS";

export const GET_FREELANCER_CLIENT_REVIEWS_FAIL =
  " GET_FREELANCER_CLIENT_REVIEWS_FAIL";

export const GET_FREELANCER_CLIENT_REVIEWS_REQUEST =
  " GET_FREELANCER_CLIENT_REVIEWS_REQUEST";

export const GET_ALL_JOBS_PROPOSALS_FOR_FREELANCER_SUCCESS =
  " GET_ALL_JOBS_PROPOSALS_FOR_FREELANCER_SUCCESS";
export const GET_ALL_JOBS_PROPOSALS_FOR_FREELANCER_FAIL =
  " GET_ALL_JOBS_PROPOSALS_FOR_FREELANCER_FAIL";
export const GET_ALL_JOBS_PROPOSALS_FOR_FREELANCER_REQUEST =
  " GET_ALL_JOBS_PROPOSALS_FOR_FREELANCER_REQUEST";

export const DELETE_JOB_PROPOSAL_SUCCESS = " DELETE_JOB_PROPOSAL_SUCCESS";
export const DELETE_JOB_PROPOSAL_FAIL = " DELETE_JOB_PROPOSAL_FAIL";
export const DELETE_JOB_PROPOSAL_REQUEST = " DELETE_JOB_PROPOSAL_REQUEST";

// Proposals

export const ACCEPT_PROPOSAL_SUCCESS = "ACCEPT_PROPOSAL_SUCCESS";
export const ACCEPT_PROPOSAL_FAIL = "ACCEPT_PROPOSAL_FAIL";
export const ACCEPT_PROPOSAL_REQUEST = "ACCEPT_PROPOSAL_REQUEST";

export const REJECT_PROPOSAL_SUCCESS = "REJECT_PROPOSAL_SUCCESS";
export const REJECT_PROPOSAL_FAIL = "REJECT_PROPOSAL_FAIL";
export const REJECT_PROPOSAL_REQUEST = "REJECT_PROPOSAL_REQUEST";

export const EDIT_PROPOSAL_SUCCESS = "EDIT_PROPOSAL_SUCCESS";
export const EDIT_PROPOSAL_FAIL = "EDIT_PROPOSAL_FAIL";
export const EDIT_PROPOSAL_REQUEST = "EDIT_PROPOSAL_REQUEST";

// Clients
export const GET_CLIENT_PROFILE_SUCCESS = "GET_CLIENT_PROFILE_SUCCESS";
export const GET_CLIENT_PROFILE_FAIL = "GET_CLIENT_PROFILE_FAIL";
export const GET_CLIENT_PROFILE_REQUEST = "GET_CLIENT_PROFILE_REQUEST";

export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_FAIL = "ADD_PAYMENT_FAIL";
export const ADD_PAYMENT_REQUEST = "ADD_PAYMENT_REQUEST";

export const GET_PAYMENT_FAIL = "GET_PAYMENT_FAIL";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST";

export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";
export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";

export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS";
export const SUBMIT_REVIEW_FAIL = "SUBMIT_REVIEW_FAIL";
export const SUBMIT_REVIEW_REQUEST = "SUBMIT_REVIEW_REQUEST";

export const UPDATE_CLIENT_PROFILE_SUCCESS = "UPDATE_CLIENT_PROFILE_SUCCESS";
export const UPDATE_CLIENT_PROFILE_FAIL = "UPDATE_CLIENT_PROFILE_FAIL";
export const UPDATE_CLIENT_PROFILE_REQUEST = "UPDATE_CLIENT_PROFILE_REQUEST";

export const UPDATE_CLIENT_ACCOUNT_SUCCESS = "UPDATE_CLIENT_ACCOUNT_SUCCESS";
export const UPDATE_CLIENT_ACCOUNT_FAIL = "UPDATE_CLIENT_ACCOUNT_FAIL";
export const UPDATE_CLIENT_ACCOUNT_REQUEST = "UPDATE_CLIENT_ACCOUNT_REQUEST";

export const RESET_CLIENT_PASSWORD_SUCCESS = "RESET_CLIENT_PASSWORD_SUCCESS";
export const RESET_CLIENT_PASSWORD_FAIL = "RESET_CLIENT_PASSWORD_FAIL";
export const RESET_CLIENT_PASSWORD_REQUEST = "RESET_CLIENT_PASSWORD_REQUEST";

export const VERIFY_CLIENT_TOKEN_SUCCESS = "VERIFY_CLIENT_TOKEN_SUCCESS";
export const VERIFY_CLIENT_TOKEN_FAIL = "VERIFY_CLIENT_TOKEN_FAIL";
export const VERIFY_CLIENT_TOKEN_REQUEST = "VERIFY_CLIENT_TOKEN_REQUEST";

export const CREATE_NEW_CLIENT_CONVERSATION_SUCCESS =
  "CREATE_NEW_CLIENT_CONVERSATION_SUCCESS";
export const CREATE_NEW_CLIENT_CONVERSATION_FAIL =
  "CREATE_NEW_CLIENT_CONVERSATION_FAIL";
export const CREATE_NEW_CLIENT_CONVERSATION_REQUEST =
  "CREATE_NEW_CLIENT_CONVERSATION_REQUEST";

export const GET_CLIENT_MESSAGES_SUCCESS = "GET_CLIENT_MESSAGES_SUCCESS";
export const GET_CLIENT_MESSAGES_FAIL = "GET_CLIENT_MESSAGES_FAIL";
export const GET_CLIENT_MESSAGES_REQUEST = "GET_CLIENT_MESSAGES_REQUEST";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";

export const FORGET_CLIENT_PASSWORD_SUCCESS = "FORGET_CLIENT_PASSWORD_SUCCESS";
export const FORGET_CLIENT_PASSWORD_FAIL = "FORGET_CLIENT_PASSWORD_FAIL";
export const FORGET_CLIENT_PASSWORD_REQUEST = "FORGET_CLIENT_PASSWORD_REQUEST";

export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAIL = "EMAIL_VERIFICATION_FAIL";

export const GET_ALL_CLIENT_REPORTS_SUCCESS = "GET_ALL_CLIENT_REPORTS_SUCCESS";
export const GET_ALL_CLIENT_REPORTS_FAIL = "GET_ALL_CLIENT_REPORTS_FAIL";
export const GET_ALL_CLIENT_REPORTS_REQUEST = "GET_ALL_CLIENT_REPORTS_REQUEST";

export const DELETE_CLIENT_ACCOUNT_SUCCESS = "DELETE_CLIENT_ACCOUNT_SUCCESS";
export const DELETE_CLIENT_ACCOUNT_FAIL = "DELETE_CLIENT_ACCOUNT_FAIL";
export const DELETE_CLIENT_ACCOUNT_REQUEST = "DELETE_CLIENT_ACCOUNT_REQUEST";

export const GET_ALL_CLIENT_BLOGS_SUCCESS = "GET_ALL_CLIENT_BLOGS_SUCCESS";
export const GET_ALL_CLIENT_BLOGS_FAIL = "GET_ALL_CLIENT_BLOGS_FAIL";
export const GET_ALL_CLIENT_BLOGS_REQUEST = "GET_ALL_CLIENT_BLOGS_REQUEST";

export const SEND_OTP_CLIENT_SUCCESS = "Send_OTP_CLIENT_SUCCESS";
export const SEND_OTP_CLIENT_FAIL = "Send_OTP_CLIENT_FAIL";
export const SEND_OTP_CLIENT_REQUEST = "Send_OTP_CLIENT_REQUEST";

export const VERIFY_CLIENT_EMAIL_SUCCESS = "VERIFY_CLIENT_EMAIL_SUCCESS";
export const VERIFY_CLIENT_EMAIL_FAIL = "VERIFY_CLIENT_EMAIL_FAIL";
export const VERIFY_CLIENT_EMAIL_REQUEST = "VERIFY_CLIENT_EMAIL_REQUEST";

export const READ_CLIENT_NOTIFICATION_SUCCESS =
  " READ_CLIENT_NOTIFICATION_SUCCESS";
export const READ_CLIENT_NOTIFICATION_FAIL = " READ_CLIENT_NOTIFICATION_FAIL";
export const READ_CLIENT_NOTIFICATION_REQUEST =
  " READ_CLIENT_NOTIFICATION_REQUEST";

// Notifications
export const READ_NOTIFICATION_SUCCESS = "READ_NOTIFICATION_SUCCESS";
export const READ_NOTIFICATION_FAIL = "READ_NOTIFICATION_FAIL";

// Blogs
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS";
export const GET_ALL_BLOGS_FAIL = "GET_ALL_BLOGS_FAIL";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const REPLY_COMMENT_SUCCESS = "REPLY_COMMENT_SUCCESS";
export const REPLY_COMMENT_FAIL = "REPLY_COMMENT_FAIL";

// General
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";

// Guest

export const GET_ALL_GUEST_JOBS_SUCCESS = "GET_ALL_GUEST_JOBS_SUCCESS";
export const GET_ALL_GUEST_JOBS_FAIL = "GET_ALL_GUEST_JOBS_FAIL";
export const GET_ALL_GUEST_JOBS_REQUEST = "GET_ALL_GUEST_JOBS_REQUEST";

export const GET_ALL_GUEST_EXCHANGE_SKILLS_SUCCESS =
  "GET_ALL_GUEST_EXCHANGE_SKILLS_SUCCESS";
export const GET_ALL_GUEST_EXCHANGE_SKILLS_FAIL =
  "GET_ALL_GUEST_EXCHANGE_SKILLS_FAIL";
export const GET_ALL_GUEST_EXCHANGE_SKILLS_REQUEST =
  "GET_ALL_GUEST_EXCHANGE_SKILLS_REQUEST";

export const GET_ALL_GUEST_FREELANCERS_SUCCESS =
  " GET_ALL_GUEST_FREELANCERS_SUCCESS";
export const GET_ALL_GUEST_FREELANCERS_FAIL = " GET_ALL_GUEST_FREELANCERS_FAIL";
export const GET_ALL_GUEST_FREELANCERS_REQUEST =
  " GET_ALL_GUEST_FREELANCERS_REQUEST";

export const GET_GUEST_REVIEWS_SUCCESS = " GET_GUEST_REVIEWS_SUCCESS";
export const GET_GUEST_REVIEWS_FAIL = "GET_GUEST_REVIEWS_FAIL";
export const GET_GUEST_REVIEWS_REQUEST = "GET_GUEST_REVIEWS_REQUEST";
